components:
  schemas: {}
info:
  contact:
    email: developers@utelly.com
    name: API Support
  description: Api to manage DM0 entities
  title: dm0
  version: v1
openapi: 3.0.0
paths:
  '/data_matches/{type}':
    get:
      operationId: v1.data_matches.get
      parameters:
        - in: query
          name: group_uid
          required: true
          schema:
            type: string
        - in: query
          name: source
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    items:
                      - deleted: true
                        destination_name: gracenote_gracenote
                        destination_uid: '3232'
                        matcher: ManualMatcher
                        source_name: iva_iva
                        source_uid: '123'
              schema:
                additionalProperties: false
                description: ''
                properties:
                  items:
                    items:
                      additionalProperties: false
                      properties:
                        deleted:
                          type: boolean
                        destination_name:
                          minLength: 1
                          type: string
                        destination_uid:
                          minLength: 1
                          type: string
                        matcher:
                          type: string
                        source_name:
                          minLength: 1
                          type: string
                        source_uid:
                          minLength: 1
                          type: string
                      required:
                        - source_name
                        - source_uid
                        - destination_name
                        - destination_uid
                        - deleted
                      type: object
                    minItems: 1
                    type: array
                    uniqueItems: true
                required:
                  - items
                type: object
          description: OK
      summary: Get data matches
      tags:
        - Dm0 Management
    parameters:
      - in: path
        name: type
        required: true
        schema:
          enum:
            - people
            - shows
          type: string
    post:
      operationId: v1.data_matches.post
      requestBody:
        content:
          application/json:
            examples:
              '1':
                value:
                  deleted: true
                  destination_name: gracenote_gracenote
                  destination_uid: '3232'
                  matcher: ManualMatcher
                  source_name: iva_iva
                  source_uid: '123'
            schema:
              additionalProperties: false
              description: ''
              properties:
                deleted:
                  type: boolean
                destination_name:
                  minLength: 1
                  type: string
                destination_uid:
                  minLength: 1
                  type: string
                matcher:
                  type: string
                source_name:
                  minLength: 1
                  type: string
                source_uid:
                  minLength: 1
                  type: string
              required:
                - source_name
                - source_uid
                - destination_name
                - destination_uid
                - deleted
                - matcher
              type: object
      responses:
        '201':
          content:
            application/json:
              examples:
                '1':
                  value:
                    deleted: true
                    destination_name: gracenote_gracenote
                    destination_uid: '3232'
                    matcher: ManualMatcher
                    source_name: iva_iva
                    source_uid: '123'
              schema:
                additionalProperties: false
                description: ''
                properties:
                  deleted:
                    type: boolean
                  destination_name:
                    minLength: 1
                    type: string
                  destination_uid:
                    minLength: 1
                    type: string
                  matcher:
                    type: string
                  source_name:
                    minLength: 1
                    type: string
                  source_uid:
                    minLength: 1
                    type: string
                required:
                  - source_name
                  - source_uid
                  - destination_name
                  - destination_uid
                  - deleted
                type: object
          description: Created
      summary: Create new data match
      tags:
        - Dm0 Management
  '/people/{uid}':
    get:
      operationId: v1.person.get
      parameters:
        - in: query
          name: source
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    full_name: hello
                    pictures:
                      - url: 'https://mydomain.com/image.jpg'
                    uid: '23232'
              schema:
                additionalProperties: false
                description: ''
                properties:
                  full_name:
                    minLength: 1
                    type: string
                  pictures:
                    items:
                      additionalProperties: false
                      properties:
                        url:
                          minLength: 1
                          type: string
                      required:
                        - url
                      type: object
                    minItems: 1
                    type: array
                    uniqueItems: true
                  uid:
                    minLength: 1
                    type: string
                required:
                  - uid
                  - full_name
                  - pictures
                type: object
          description: OK
      summary: Get person
      tags:
        - Dm0 Management
    parameters:
      - in: path
        name: uid
        required: true
        schema:
          type: string
  '/shows/{uid}':
    get:
      operationId: v1.show.get
      parameters:
        - in: query
          name: source
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    actors:
                      - full_name: Leonardo
                    pictures:
                      - url: 'https://mydomain.com/image.jpg'
                    primary_name: hello
                    uid: '23232'
              schema:
                additionalProperties: false
                description: ''
                properties:
                  actors:
                    items:
                      additionalProperties: false
                      properties:
                        full_name:
                          type: string
                      required:
                        - full_name
                      type: object
                    type: array
                  pictures:
                    items:
                      additionalProperties: false
                      properties:
                        url:
                          minLength: 1
                          type: string
                      required:
                        - url
                      type: object
                    minItems: 1
                    type: array
                    uniqueItems: true
                  primary_name:
                    minLength: 1
                    type: string
                  release_year:
                    type: integer
                  uid:
                    type: string
                required:
                  - primary_name
                  - pictures
                  - uid
                  - actors
                type: object
          description: OK
      summary: Get show
      tags:
        - Dm0 Management
    parameters:
      - in: path
        name: uid
        required: true
        schema:
          type: string
  '/data_quality/samples/{guid}':
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  guid:
                    type: string
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        guid:
                          type: string
                        matches:
                          type: array
                          items:
                            type: object
                            properties:
                              guid:
                                type: string
                              matcher:
                                type: string
                        unmatches:
                          type: array
                          items:
                            type: object
                            properties:
                              guid:
                                type: string
                              matcher:
                                type: string
                x-examples:
                  example-1:
                    guid: abc123
                    items:
                      - guid: cbd456
                        matches:
                          - guid: cbd789
                            matcher: ZipMatcher
                        unmatches:
                          - guid: cbe034
                            matcher: ZipMatcher
                      - guid: efg456
                        matches:
                          - matcher: ZipMatcher
                            guid: d3e330
                        unmatches:
                          - matcher: ManualMatcher
                            guid: efg789
              examples:
                '1':
                  value:
                    guid: abc123
                    items:
                      - guid: cbd456
                        matches:
                          - guid: cbd789
                            matcher: ZipMatcher
                        unmatches:
                          - guid: cbe034
                            matcher: ZipMatcher
                      - guid: efg456
                        matches:
                          - matcher: ZipMatcher
                            guid: d3e330
                        unmatches:
                          - matcher: ManualMatcher
                            guid: efg789
      operationId: v1.data_quality.samples.get
      description: Retrieve a list of entities and their matches for review.
      tags:
        - Dm0 Management
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
        description: Identifier for a sample created for review
  '/data_quality/verify/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
        description: Guid for creative_work to be verified
    post:
      summary: ''
      operationId: v1.data_qaulity.verify.post
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  verified:
                    type: array
                    items:
                      type: object
                      properties:
                        guid:
                          type: string
                  statistics:
                    type: object
                    properties:
                      verified:
                        type: integer
                      pending:
                        type: integer
                      manual_matches:
                        type: integer
                      manual_unmatches:
                        type: integer
                      veried_matches:
                        type: integer
                      verified_unmatches:
                        type: integer
                x-examples:
                  example-1:
                    verified:
                      - guid: cbd456
                    statistics:
                      verified: 3
                      pending: 97
                      manual_matches: 1
                      manual_unmatches: 1
                      veried_matches: 1
                      verified_unmatches: 0
              examples:
                '1':
                  value:
                    verified:
                      - guid: cbd456
                    statistics:
                      verified: 3
                      pending: 97
                      manual_matches: 1
                      manual_unmatches: 1
                      veried_matches: 1
                      verified_unmatches: 0
      tags:
        - Dm0 Management
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  guid: cbd456
                  verified: false
                  unmatch:
                    - cbd789
                  match:
                    - dde298
              properties:
                guid:
                  type: string
                verified:
                  type: boolean
                unmatch:
                  type: array
                  items:
                    type: string
                match:
                  type: array
                  items:
                    type: string
              required:
                - guid
                - verified
            examples:
              '1':
                value:
                  guid: cbd456
                  verified: false
                  unmatch:
                    - cbd789
                  match:
                    - dde298
      description: Verify that the specified item is correctly matched or unmatched. If flagged as incorrcect the optionally include guids of items to match or unmatch.
servers:
  - description: prod
    url: 'https://services.utelly.com/dm0_manager/v1'
  - description: staging
    url: 'https://staging-services.utelly.com/dm0_manager/v1'
  - description: dev
    url: 'https://dev-services.utelly.com/dm0_manager/v1'
tags:
  - name: utelly_services
