openapi: 3.0.0
info:
  title: log_manager
  version: v1
  description: Log manager for the Utelly API platform
servers:
  - url: 'https://utellapis.com/log_manager/v1'
    description: prod
  - url: 'https://dev.utellapis.com/log_manager/v1'
    description: dev
  - url: 'https://staging.utellapis.com/log_manager/v1'
    description: staging
paths:
  /log:
    post:
      summary: Add a Log entry
      operationId: v1.log.post_log
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  status_code:
                    type: integer
                  log:
                    $ref: '#/components/schemas/Log'
                required:
                  - status_code
                  - log
              examples:
                '1':
                  value:
                    status_code: 200
                    log:
                      timestamp: 1583934547
                      variant: utellygn
                      app_key: 36a637a56e184748b0470e50e6242901
                      system_name: user_manager
                      version: 2
                      payload:
                        message: pipeline successfully created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Log'
            examples:
              '1':
                value:
                  timestamp: 1583934547
                  variant: utellygn
                  app_key: 36a637a56e184748b0470e50e6242901
                  system_name: user_manager
                  version: 2
                  payload:
                    message: pipeline successfully created
      security:
        - Authorization: []
      description: Add a Log entry
      tags:
        - Log Management
  /logs:
    post:
      summary: Batch add Log entries
      operationId: v1.logs.post_logs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  status_code:
                    type: number
                  logs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Log'
                required:
                  - status_code
                  - logs
              examples:
                '1':
                  value:
                    status_code: 200
                    logs:
                      - timestamp: 1583934547
                        variant: utellygn
                        app_key: 36a637a56e184748b0470e50e6242901
                        system_name: user_manager
                        version: 2
                        payload:
                          message: pipeline successfully created
      security:
        - Authorization: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              uniqueItems: false
              items:
                $ref: '#/components/schemas/Log'
            examples:
              '1':
                value:
                  - timestamp: 1583934547
                    variant: utellygn
                    app_key: 36a637a56e184748b0470e50e6242901
                    system_name: user_manager
                    version: 2
                    payload:
                      message: pipeline successfully created
      description: Batch add Log entries
      tags:
        - Log Management
      parameters: []
    parameters: []
components:
  schemas:
    Log:
      title: Log
      type: object
      x-examples:
        '1':
          timestamp: 1583934547
          variant: utellygn
          app_key: 36a637a56e184748b0470e50e6242901
          system_name: user_manager
          version: 2
          payload:
            message: pipeline successfully created
      properties:
        timestamp:
          type: integer
        variant:
          type: string
        app_key:
          type: string
        payload:
          type: object
        system_name:
          type: string
        version:
          type: number
      required:
        - timestamp
        - variant
        - app_key
        - payload
        - system_name
        - version
      x-tags:
        - Models
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
      description: ''
      x-apikeyInfoFunc: security.check_token
